#!/bin/bash

set -e
set -x

options=$(getopt -o hp:n:S: -l help,rootfs:,mapped-uid:,mapped-gid:,path:,name:,auth-key: -- "$@")
if [ $? -ne 0 ]; then
        usage $(basename $0)
    exit 1
fi
eval set -- "$options"

while true
do
    case "$1" in
        -h|--help)      usage $0 && exit 0;;
        -p|--path)      path=$2; shift 2;;
        --rootfs)       rootfs=$2; shift 2;;
        -n|--name)      name=$2; shift 2;;
#        -S|--auth-key)  auth_key=$2; shift 2;;
        --)             shift 1; break ;;
        *)              break ;;
    esac
done


function die() {
    echo $@
    exit 1
}

[ -z "$rootfs" ] && die "what rootfs?"
[ -z "$path" ] && die "what path?"
[ -z "$name" ] && die "what name?"

cd $rootfs

mkdir -p -v $rootfs/dev
mkdir -p -v $rootfs/sys
mkdir -p -v $rootfs/proc

gzip -dc /home/patrick/svn/github/patrickangusjohngrant/Uvwpmacoh/initramfs/uvwpmacoh.cpio.gz | cpio -i
cp /home/patrick/svn/github/patrickangusjohngrant/Uvwpmacoh/filesystem/init $rootfs/sbin/init.lxc

mkdir -p -v $path

echo $path/config

cat <<EOF > $path/config
lxc.rootfs = $rootfs
lxc.utsname = $name
lxc.pts = 1024
lxc.kmsg = 0
lxc.cap.drop = sys_module mac_admin mac_override sys_time
lxc.init_cmd = /sbin/init.lxc
EOF

